version: '3'
networks:
  \srv\beego-app_network_compose:
    driver: bridge 
services:
  \srv\beego-app:
    container_name: \srv\beego-app
    build: .
    restart: unless-stopped
    networks:
      \srv\beego-app_network_compose:
    ports:
    - "8080:8080"
